### ISSUE TITLE
Inconsistent ensembl info display

### ISSUE THREAD

**Issue by eudesbarbosa** [bihealth/varfish-server#156]
**Issue**
Internally VarFish displays gene/transcript information associated with GRCh37, but it displays results from GRCh38 while querying Ensembl. This mix leads to confusion.

**Example**
Gene PPP2R2C (chr4:6,349,605)
The link provided by VarFish refers to GRCh38 :
http://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000074211;r=4:6320578-6563600
...but displayed internally GRCh37:
http://grch37.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000074211;r=4:6322305-6565327

**Expected behaviour**
Consistent information displayed internally and queried from external sources, i.e., same genome version.

**Additional info**
Issue also impacts VariantValidator:
https://rest.variantvalidator.org/VariantValidator/variantvalidator/hg19/chr4-6349605-C-T/all?content-type=application%2Fjson
https://rest.variantvalidator.org/VariantValidator/variantvalidator/hg38/chr4-6347878-C-T/all?content-type=application%2Fjson

**Comment by stolpeo** [comment]
### Root Cause Analysis

We do two link-outs to Ensembl, one for the variant and one for the gene. As it was not specified which link-out was meant, I checked both:

**Linkout for the variant**

![image](https://user-images.githubusercontent.com/1266531/145003111-5567d31e-1292-4436-81f5-6dc8a2bc4400.png)

This links correctly to the GRCh37 genome.

**Linkout for gene in fold-out**

``Ensembl ID`` in the gene card links wrongly to the GRCh38.

### Resolution Proposal

Linkout to ensembl gene needs to be changed.

**Affected Components**

- VarFish server

**Affected Modules/Files**

- geneinfo/templates/gene_info/gene_info.html

**Required Architectural Changes**

None.

**Resolution Sketch**

www.ensembl.org to grch37.ensembl.org

**Comment by stolpeo** [comment]
@eudesbarbosa I fixed the broken link-out (at least to my understanding). I couldn't follow the issue with variantvalidator. this sounds like an separate issue. In this case, could you please open a new bug report for this?

**Comment by eudesbarbosa** [comment]
@stolpeo, I scan the merge request and just to clarify, is the used link depending somehow on the **Genomebuild** info? I'd assume that we have already samples processed with GRCh38 and that could lead to problems for those.

Regarding the VariantValidator, I will write a different issue.

**Comment by stolpeo** [comment]
@eudesbarbosa Yes, the link is based on genomebuild. Right now, the GRCh38 development branch is not yet merged into the main branch. I would prefer to have the link switch in the GRCh38 branch rather than integrating GRCh38 related stuff before introduction of the actual feature.

**Comment by eudesbarbosa** [comment]
Thank you for the clarification.

Regarding VariantValidator, I could not replicate the error. It seems the transcripts displayed in the query is that same as the ones displayed in the 'Transcript information' table. Plus, the warning displayed can be ignored - according to their [website](https://www.variantvalidator.org/help/instructions/):
_RefSeqGene record not available:
Only some genes have an NCBI RefSeqGene record. This warning simply indicates that no RefSeqGene record exists for the gene in which the variant that is being validated resides._

**Comment by stolpeo** [comment]
I changed my mind and included the switch anyway after revising @holtgrewe MR #220 and not finding a change in the according lines. So this commit should make the ensembl link-out future proof.
