### ISSUE TITLE
Add all extra annotations to Excel download

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#495]
**Is your feature request related to a problem? Please describe.**
We added support for displaying extra annotations in the results table with #242. However, they are missing from the Excel export.

**Describe the solution you'd like**
All extra annotations that can be displayed in the result table rows should also go to the Excel file download.

**Describe alternatives you've considered**
N/A

**Additional context**
- #242

**Comment by incardon** [comment]
**Implementation Proposal**
RowWithExtraAnno that wrap the result table in order to make the exporters working with the additional columns.

The additional columns are added in the base exported when extra anno option is active, the expansion is based on the fields in the database

**Affected Components**
Exports


**Affected Modules/Files**
variants/file_export.py, variants/file_export.py, variants/models.py variants/tests/test_file_export.py

**Required Architectural Changes**
A RowWithExtraAnno must be created

**Implementation Sketch**
Create a RowWithExtraAnno that wrap the result, to make all the exporter working without changing their code. In the base exporter we add the colums coming from the Extra anno fields

**Comment by holtgrewe** [comment]
I think we should remove the configuration setting `VARFISH_ENABLE_EXTRA_ANNOS` and enable it by default. Could you add this to the implementation sketch and adjust #525.
