### ISSUE TITLE
Logic error in query generation for flags

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/varfish-server#502]
**Describe the bug**
The following logic is clearly wrong.

```python
class ExtendQueryPartsFlagsJoinAndFilter(ExtendQueryPartsFlagsJoin):
    def extend_conditions(self, _query_parts):
        """Build WHERE clause for the query based on the ``SmallVariantFlags`` and ``SmallVariantComment``."""
        terms = []
        # Add terms for the simple, boolean-valued flags.
        flag_names = ("bookmarked", "candidate", "final_causative", "for_validation")
        for flag in flag_names:
            flag_name = "flag_%s" % flag
            if self.kwargs.get(flag_name):
                terms.append(column(flag_name))
#BEGIN BOGUS
        if self.kwargs.get("flag_simple_empty"):
            terms.append(and_(not_(column("flag_%s" % flag))))
#END BOGUS
```

**To Reproduce**
N/A

**Expected behavior**
N/A

**Additional context**
This clearly is a logic error as the lower `flag` refers to the `flag` from the above loop value. This needs review and fix.

We should backport the fix to `anthenea`.

**Comment by stolpeo** [comment]
## RCA

Affected is the filter setting for the user flags:

![image](https://user-images.githubusercontent.com/1266531/173077556-896d7225-320c-41ba-b00c-e8d0b53b8aa6.png)

The description for the flag: "When set (default) then variants that have no simple flag set are included in the result"

However, there is no simple flag that the user can set (`flag_no_simple`). It is unclear whether this setting can be removed at all.

**Comment by stolpeo** [comment]
OK I assume that it is not actually a flag, but it means that it should be selected when none of the other flags are set.

**Comment by stolpeo** [comment]
The question is how the filter should behave when everything is selected (as it is by default).

**Comment by stolpeo** [comment]
**Resolution Proposal**
This ticket addresses 2 issues.

1. the `no known disease`, `segregates` and `doesn't segregate` flags weren't reflected in the filter query and in the file export.
2. the logic error is to be fixed in a way that not only the setting of no simple flag (flag==False) is addressed but also variants that have no flag at all (flag==None).

**Affected Components**
VarFish server

**Affected Modules/Files**
- `queries.py`
- Everywhere where the "recently" added flags are missing

**Required Architectural Changes**
None

**Required Database Changes**
None

**Backport Possible?**
Yes

**Resolution Sketch**
- Fix logic error
- Introduce `flag_doesnt_segregate`, `flag_segregates` and `flag_no_disease_association` in file export and filter query
