### ISSUE TITLE
Linkout to HGMD Professional

### ISSUE THREAD

**Issue by your-highness** [bihealth/varfish-server#576]
**Is your feature request related to a problem? Please describe.**
VarFish already provides many link outs. However, no link to HGMD professional is included. This is no violation of the license agreement because check for license is done after link is opened.

**Describe the solution you'd like**
Similar to linkouts to UCSC, EnsEMBl _etc._ a link to HGMD Professional should be included:
![image](https://user-images.githubusercontent.com/1949888/178541291-18bc4d01-9648-4672-a455-4f66040f6639.png)

The URL format follows this convention (needs to checked):
| Feature | URL |
| -------- | ----- |
| Genes | https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro/gene.php?gene=BRCA2 |
| dbSNP-ID | https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro/mutsearch.php?input=rs80358547&mut=Y&poly=Y&search4=dbSNP+identifier  |
| hg19 coordinate | https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro/mutsearch.php?input=chr13%3A32316462&mut=Y&poly=Y&search4=hg19+coordinate |

**Describe alternatives you've considered**
Using variante coordinates and manually check HGMD professional for variant annotations.

**Additional context**
None.

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Adding this is straightforward. We should have a global configuration variable to enable another link-out section(s) for the by-gene and by-variant link-outs to HGMD as some sites do not have licensed HGMD and it clutters the UI a bit. Otherwise, we just need to change the template.

**Affected Components**
VarFish server

**Affected Modules/Files**
- `variants/templates/variants/filter_result/row.html`

**Required Architectural Changes**
None

**Required Database Changes**
None

**Backport Possible?**
Yes

**Resolution Sketch**
- Add setting `VARFISH_ENABLE_HGMD_LINKOUT` defaulting to `0`/`false`
- Update the affected `row.html` file mentioned above

**Comment by holtgrewe** [comment]
@your-highness could you confirm that `hg38+coordinate` also works?

**Comment by xiamaz** [comment]
It would be great if we could have admin configurable linkouts. For example this could allow alternative domains, if certain tools are installed on-site.

**Comment by your-highness** [comment]
> @your-highness could you confirm that `hg38+coordinate` also works?

Yes. That is correct!

I just checked if `mutsearch.php` (dbSNP- & Coordinate-based) allows supplying arguments via URL but it does not seem to work as described. I need to do some research what the correct URL scheme for PHP is. 
Gene-based Lookup works correctly when HGNC Gene Symbols are used.

> It would be great if we could have admin configurable linkouts. For example this could allow alternative domains, if certain tools are installed on-site.

I second that!

**Comment by holtgrewe** [comment]
OK, I added the description of `VARFISH_HGMD_URL_PREFIX` to the Implementation Proposal.

**Comment by holtgrewe** [comment]
OK, some screenshot from current implementation.

![image](https://user-images.githubusercontent.com/521780/178725979-e46bdc45-37a4-46fa-ba30-cd68e8928fb6.png)

![image](https://user-images.githubusercontent.com/521780/178726061-7cf5f2e1-b174-4775-9756-d473da8fe6d9.png)

@your-highness can you confirm that the following two links work?

https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro/gene.php?gene=GPSM2

https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro//mutsearch.php?input=chr1%3A109466760&mut=Y&poly=Y&search4=hg19+coordinate

**Comment by your-highness** [comment]
> @your-highness can you confirm that the following two links work?
> https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro/gene.php?gene=GPSM2

Works as intended.
 
> https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro//mutsearch.php?input=chr1%3A109466760&mut=Y&poly=Y&search4=hg19+coordinate

Does not work correctly:
![image](https://user-images.githubusercontent.com/1949888/178726698-4b476ebd-9c96-4a20-8f9e-065e0ed1ec66.png)

I assume the PHP GET is missing some argument. I have to get my head around that when I have time. Mayb @xiamaz has an idea?

**Comment by holtgrewe** [comment]
The problem is the double-slash, probably, you you try

https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro/mutsearch.php?input=chr1%3A109466760&mut=Y&poly=Y&search4=hg19+coordinate

**Comment by your-highness** [comment]
> The problem is the double-slash, probably, you you try
> 
> https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro/mutsearch.php?input=chr1%3A109466760&mut=Y&poly=Y&search4=hg19+coordinate

Same result.

I am not a PHP expert and there might be some variable transmitted which is missing now.

**Comment by holtgrewe** [comment]
Hm, but the original URL you posted works?

https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro/mutsearch.php?input=chr13%3A32316462&mut=Y&poly=Y&search4=hg19+coordinate

**Comment by your-highness** [comment]
No. Like said above this needs some adaption. I count on @xiamaz for help on this issue. Please check!

**Comment by xiamaz** [comment]
`mutsearch.php` does not seem to support GET requests. It only supports POST (at least for me). @your-highness How did you get the mutsearch URL?

Otherwise the main issue with sending POST requests is that some essential cookies will be missing and one will be redirected to the login page.

If one has access to some kind of proxy for persisting a HGMD session the following would work:

```
import requests

data = {
    'input': 'chr5:36985782',
    'mut': 'Y',
    'poly': 'Y',
    'search4': 'hg19 coordinate',
}

response = requests.post('https://my.qiagendigitalinsights.com/bbp/view/hgmd/pro/mutsearch.php', data=data, proxies={"http": None,})
```

All this might get rather complicated rather quickly. For the most common use-case, a working linkout based on gene name should be enough. The variant-based interface should not be necessary.

**Comment by your-highness** [comment]
> All this might get rather complicated rather quickly. **For the most common use-case, a working linkout based on gene name should be enough. The variant-based interface should not be necessary.**

@holtgrewe Let's do it like this: Every variant points to the HGNC gene entry in HGMD Professional.
