### ISSUE TITLE
Allow VariantValidator, MutationTaster from VariantAnnotation tab

### ISSUE THREAD

**Issue by xiamaz** [bihealth/varfish-server#709]
**Is your feature request related to a problem? Please describe.**
During investigation of variants one often would like to view a variant in detail after filtering and utilize some tools on a variant (including VariantValidator for HGVS code)

**Describe the solution you'd like**
Actions for individual variants should be available from the Variant Annotation tab in a case.

**Describe alternatives you've considered**
Refiltering variants. It can be difficult to retrace where bookmarked variants have been found before. So this can be very time consuming.

**Comment by holtgrewe** [comment]
We will not be able to support MutationDistiller for now, but link-outs to MutationDistiller and VariantValidator are easy to support.

**Comment by xiamaz** [comment]
Sorry, meant MutationTaster. Just the linkouts that are available in the small variant filtering view would be great. If the components are portable enough, reusing the row from the small variant filter view would give us all features we need.

**Comment by holtgrewe** [comment]
> Sorry, meant MutationTaster. Just the linkouts that are available in the small variant filtering view would be great. If the components are portable enough, reusing the row from the small variant filter view would give us all features we need.

perfect

**Comment by stolpeo** [comment]
@xiamaz All the links moved to the details card because we discontinued the dropdown menus in the table as they were causing more harm than they use. The card is available in the case details as well. In addition, I added the link-out to MT2021 in the table row for quick access. Does that work for you?

![Screenshot from 2023-03-06 14-51-23](https://user-images.githubusercontent.com/1266531/223136422-e02a56f0-9cf8-431b-a2f4-fecf70c129f7.png)
